# Generated by Django 4.2.6 on 2023-12-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_alter_category_options_alter_sneakers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Знижка'),
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Ціна'),
        ),
    ]
