# Generated by Django 4.2.6 on 2024-01-06 18:19

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0024_alter_sneakers_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
