# Generated by Django 4.2.6 on 2024-01-11 11:10

import colorfield.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('goods', '0025_alter_sneakers_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Ціна зі знижкою'),
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
