# Generated by Django 4.2.6 on 2024-01-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0026_alter_sneakers_color_alter_sneakers_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кількість'),
        ),
    ]
