# Generated by Django 4.2.6 on 2024-01-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0031_alter_category_options_alter_category_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sneakers', to='goods.category', verbose_name='Категорія'),
        ),
    ]
