# Generated by Django 4.2.6 on 2024-01-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0036_remove_sneakers_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneakers',
            name='quantity',
        ),
        migrations.AddField(
            model_name='sneakersvariations',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кількість'),
        ),
    ]
