# Generated by Django 4.2.6 on 2024-01-13 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0037_remove_sneakers_quantity_sneakersvariations_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneakersvariations',
            name='sneakers',
        ),
        migrations.AddField(
            model_name='sneakers',
            name='variations',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='variations', to='goods.sneakersvariations', verbose_name='Варіації'),
        ),
    ]
