# Generated by Django 4.2.6 on 2024-01-14 09:52

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0039_remove_sneakers_variations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneakersvariations',
            name='color',
        ),
        migrations.AddField(
            model_name='sneakers',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Колір'),
        ),
    ]
