# Generated by Django 4.2.6 on 2024-01-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0040_remove_sneakersvariations_color_sneakers_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneakersvariations',
            name='color_name',
        ),
    ]
