# Generated by Django 4.2.6 on 2024-02-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0043_alter_sneakersvariations_sneakers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProductTimestamp',
        ),
    ]
