# Generated by Django 4.2.6 on 2024-02-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0045_alter_sneakersvariations_options_alter_sneakers_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakersvariations',
            name='size',
            field=models.PositiveIntegerField(verbose_name='Розмір'),
        ),
    ]
