# Generated by Django 4.2.6 on 2024-02-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0046_alter_sneakersvariations_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakersvariations',
            name='size',
            field=models.CharField(max_length=8, verbose_name='Розмір'),
        ),
    ]
