# Generated by Django 4.2.6 on 2024-07-13 17:17

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0057_review_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=0, upload_to='brand_images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
