# Generated by Django 4.2.6 on 2024-01-14 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0041_remove_sneakersvariations_color_name'),
        ('orders', '0003_alter_orderitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='goods.sneakersvariations', verbose_name='Продукт'),
        ),
    ]
