# Generated by Django 4.2.4 on 2023-09-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='price',
            field=models.TextField(blank=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='content',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
    ]
