# Generated by Django 4.2.6 on 2023-12-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_sneakers_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneakers',
            name='photo',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/%Y/%m/%d/', verbose_name='Зображення'),
        ),
    ]
