# Generated by Django 4.2.6 on 2023-12-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_remove_sneakers_photo_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.TextField(blank=True, verbose_name='Тег')),
                ('tag_slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фотографія', 'verbose_name_plural': 'Фотографії'},
        ),
        migrations.AddField(
            model_name='sneakers',
            name='tags',
            field=models.ManyToManyField(blank=True, to='goods.tagpost', verbose_name='tag'),
        ),
    ]
