# Generated by Django 4.2.6 on 2024-01-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_alter_sneakers_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Актуальна ціна'),
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
    ]
