# Generated by Django 4.2.6 on 2024-01-13 19:54

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0034_alter_sneakers_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneakers',
            name='color',
        ),
        migrations.RemoveField(
            model_name='sneakers',
            name='size',
        ),
        migrations.CreateModel(
            name='SneakersVariations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(verbose_name='Розмір')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='Колір')),
                ('color_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Назва кольору')),
                ('sneakers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='goods.sneakers', verbose_name='Кросівки')),
            ],
        ),
    ]
