# Generated by Django 4.2.6 on 2024-01-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0035_remove_sneakers_color_remove_sneakers_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneakers',
            name='variations',
        ),
    ]
