# Generated by Django 4.2.6 on 2024-01-13 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0038_remove_sneakersvariations_sneakers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneakers',
            name='variations',
        ),
        migrations.AddField(
            model_name='sneakersvariations',
            name='sneakers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='goods.sneakers', verbose_name='Кросівки'),
            preserve_default=False,
        ),
    ]
