# Generated by Django 4.2.6 on 2024-01-30 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0041_remove_sneakersvariations_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='first_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.productimage', verbose_name='Перше зображення'),
        ),
    ]
