# Generated by Django 4.2.6 on 2024-02-03 14:32

from django.db import migrations, models
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('goods', '0044_delete_userproducttimestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sneakersvariations',
            options={'ordering': ['size'], 'verbose_name': 'Варіація', 'verbose_name_plural': 'Варіації'},
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='tags',
            field=taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='sneakersvariations',
            name='size',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Розмір'),
        ),
    ]
