# Generated by Django 4.2.6 on 2024-02-06 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0047_alter_sneakersvariations_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakersvariations',
            name='sneakers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='goods.sneakers', verbose_name='Кросівки'),
        ),
    ]
