# Generated by Django 4.2.6 on 2024-02-09 13:13

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0049_alter_sneakersvariations_sneakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='product_images/%Y/%m/%d/'),
        ),
    ]
