# Generated by Django 4.2.6 on 2024-02-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0052_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Артикул'),
        ),
    ]
