# Generated by Django 4.2.6 on 2024-04-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0054_brand_sneakers_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренди'},
        ),
    ]
