# Generated by Django 4.2.4 on 2023-10-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers_shop', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='discount',
            field=models.TextField(blank=True, verbose_name='Скидка'),
        ),
    ]
