# Generated by Django 4.2.6 on 2023-12-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers_shop', '0006_tagpost_alter_productimage_options_sneakers_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneakers',
            name='tags',
        ),
        migrations.DeleteModel(
            name='TagPost',
        ),
    ]
