# Generated by Django 4.2.6 on 2023-12-21 15:39

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('sneakers_shop', '0007_remove_sneakers_tags_delete_tagpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
