# Generated by Django 4.2.6 on 2023-12-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers_shop', '0011_alter_sneakers_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=7, verbose_name='Знижка'),
        ),
        migrations.AlterField(
            model_name='sneakers',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Ціна'),
        ),
    ]
