# Generated by Django 4.2.6 on 2024-01-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers_shop', '0019_remove_variants_color_remove_variants_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers',
            name='size',
            field=models.JSONField(blank=True, max_length=128, null=True),
        ),
    ]
