# Generated by Django 4.2.6 on 2024-01-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers_shop', '0022_remove_sneakers_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='variations',
            field=models.ManyToManyField(blank=True, to='sneakers_shop.sneakers', verbose_name='Варіації'),
        ),
    ]
