# Generated by Django 4.2.6 on 2024-01-06 18:09

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers_shop', '0023_sneakers_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
