# Generated by Django 4.2.6 on 2024-01-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.JSONField(blank=True, max_length=128, null=True, verbose_name='Розмір'),
        ),
    ]
