# Generated by Django 4.2.6 on 2024-01-14 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
