# Generated by Django 4.2.6 on 2024-01-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session',
            field=models.CharField(blank=True, null=True, verbose_name='Сесія'),
        ),
    ]
