# Generated by Django 4.2.6 on 2024-01-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обробці', 'В обробці'), ('Відправлено', 'Відправлено'), ('Доставлено', 'Доставлено'), ('Скасовано', 'Скасовано')], default='В обробці', max_length=20, verbose_name='Статус'),
        ),
    ]
